source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'haml'
gem 'mysql2'
gem 'message_block'
gem 'authengine', :path => '../../../authengine'

group :development, :test do
  gem 'database_cleaner'
  gem 'launchy'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'ruby-debug'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'flexmock'
end
